// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using muhasebeprogrami.Data;

#nullable disable

namespace muhasebeprogrami.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240107081528_mig")]
    partial class mig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("muhasebeprogrami.Models.Sehir", b =>
                {
                    b.Property<int>("Sehir_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sehir_Id"), 1L, 1);

                    b.Property<string>("Sehir_Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sehir_Id");

                    b.ToTable("sehirs");
                });

            modelBuilder.Entity("muhasebeprogrami.Models.Unvan", b =>
                {
                    b.Property<int>("Unvan_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Unvan_Id"), 1L, 1);

                    b.Property<string>("Unvan_Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Unvan_Id");

                    b.ToTable("unvans");
                });
#pragma warning restore 612, 618
        }
    }
}
